### ISSUE TITLE
Todo Edit Box Doesn't Grow

### ISSUE THREAD

**Issue by NathanHeffley** [NathanHeffley/tested-todos#5]
The input box that appears when editing a todo is too short and doesn't expand to fill the whole width of the app.

Preferred solution would be to have the input field simply grow to fill the extra space in the todo item.

**Comment by NathanHeffley** [comment]
Fixed in af1e4c4363369bfaaba54c255cb0e536046412e9

**Comment by NathanHeffley** [comment]
Sorry, quickly testing some issue comment stuff, is that cool @socialgite and [google](https://google.com)?

**Comment by NathanHeffley** [comment]
<em>Whoa</em>

**Comment by nathanheffley** [comment]
_Hello_
